### ISSUE TITLE
[FIX][report_xls] Protect import. (#64)

### ISSUE THREAD

**Issue by open-net-sarl** [OCA/reporting-engine#69]
@pedrobaeza Since 65223f4a163244bae77f8493919d194428fe741b was commited i get this error:
File "/home/odoo/git/Odoo/odoo/openerp/service/report.py", line 119, in _check_report
raise openerp.osv.orm.except_orm(exc.message, exc.traceback)
except_orm: (u"type object 'report_xls' has no attribute 'xls_types'", (, AttributeError("type object 'report_xls' has no attribute 'xls_types'",), ))

Can you please fix this quickly.

**Comment by pedrobaeza** [comment]
Update your code. It was fixed in https://github.com/OCA/reporting-engine/commit/ac3a648605fbe8e3b335ba57a6972e9c9f076043

**Comment by anassahmed** [comment]
Are you sure that this is really fixed?

I still get this error:

``` python
2016-08-23 12:37:09,675 19647 ERROR test openerp.service.report: Exception: type object 'report_xls' has no attribute 'xls_types'
Traceback (most recent call last):
  File "/home/anass/Documents/workspace/odoo/odoo8/openerp/service/report.py", line 93, in go
    result, format = openerp.report.render_report(cr, uid, ids, object, datas, context)
  File "/home/anass/Documents/workspace/odoo/odoo8/openerp/report/__init__.py", line 40, in render_report
    return registry['ir.actions.report.xml'].render_report(cr, uid, ids, name, data, context)
  File "/home/anass/Documents/workspace/odoo/odoo8/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/anass/Documents/workspace/odoo/odoo8/openerp/addons/base/ir/ir_actions.py", line 156, in render_report
    return new_report.create(cr, uid, res_ids, data, context)
  File "/home/anass/.local/share/Odoo/addons/8.0/report_xls/report_xls.py", line 118, in create
    return self.create_source_xls(cr, uid, ids, data, context)
  File "/home/anass/.local/share/Odoo/addons/8.0/report_xls/report_xls.py", line 148, in create_source_xls
    self.generate_xls_report(_p, _xs, data, objs, wb)
  File "/home/anass/.local/share/Odoo/addons/8.0/account_financial_report_webkit_xls/report/partner_ledger_xls.py", line 78, in generate_xls_report
    row_data = self.xls_row_template(c_specs, [x[0] for x in c_specs])
  File "/home/anass/.local/share/Odoo/addons/8.0/report_xls/report_xls.py", line 213, in xls_row_template
    'write_cell_func': report_xls.xls_types[c[3]]})
AttributeError: type object 'report_xls' has no attribute 'xls_types'
```

Logically, at least `xls_types` should be defined inside `report_xls` class. Except if you have another class that you inherit from and has this property (which is `report_sxw`, but it doesn't have this property).

I have fixed the issue by adding this variable inside the class:

``` python
    xls_types = xls_types
```

**Comment by pedrobaeza** [comment]
Yeah, you're right, see https://github.com/OCA/reporting-engine/commit/96ac86030c2b71b4df4aac5f6a9e003f771ca9c5

**Comment by anassahmed** [comment]
Thanks, @pedrobaeza!
When should this commit be pushed to apps.odoo.com?

**Comment by pedrobaeza** [comment]
No idea. I suppose tonight. But you should work directly with git to avoid these questions.

**Comment by anassahmed** [comment]
I have no issue working with git, but our client has a server that we don't have access to, so we depend entirely on apps.odoo.com!
